source 'https://rubygems.org'

gem 'berkshelf'
gem 'foodcritic'
gem 'rake'
gem 'rspec'
gem 'rubocop'
gem 'thor', '< 0.19.3'

group :travis do
  gem 'test-kitchen', '~> 1.4'
end

group :local do
  gem 'kitchen-vagrant', '~> 0.19.0'
  gem 'vagrant-wrapper'
end
