source 'https://rubygems.org'

gem 'berkshelf'
gem 'docker'
gem 'foodcritic'
gem 'kitchen-docker'
gem 'public_suffix', '= 2.0.4'
gem 'rake'
gem 'rspec'
gem 'rubocop'
gem 'test-kitchen', '~> 1.4'
gem 'thor', '< 0.19.3'
gem 'vagrant-wrapper'

group :travis do
  #
end

group :docker do
  gem 'kitchen-docker_cli'
end

group :vagrant do
  gem 'kitchen-vagrant', '~> 0.19.0'
end
